/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventTypes_list"];
        put?: never;
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Slots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Diagnostics_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Meetings_list"];
        put?: never;
        post: operations["Meetings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Availability: {
            eventTypeId: string;
            window: components["schemas"]["AvailabilityWindow"];
            days: components["schemas"]["Day"][];
        };
        AvailabilityWindow: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        Day: {
            /** Format: date */
            date: string;
            slots: components["schemas"]["Slot"][];
        };
        Error: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            fields: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        ErrorCode: "validation_error" | "slot_taken" | "out_of_window" | "not_found";
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        EventType: {
            /** @description UUID, генерирует сервер; Владелец не вводит */
            id: string;
            /** @description Название Типа события */
            name: string;
            /** @description Описание Типа события; может отсутствовать */
            description: string | null;
            /**
             * Format: int32
             * @description Длительность в минутах, кратно 15, от 15 до 90
             */
            duration: number;
        };
        EventTypeCreate: {
            name: string;
            description?: string | null;
            /**
             * Format: int32
             * @description Длительность в минутах, кратно 15, от 15 до 90
             */
            duration: number;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Meeting: {
            id: string;
            eventTypeId: string;
            eventTypeName: string;
            /** @description Начало Встречи, ISO 8601 без часового пояса */
            start: string;
            /** @description Конец Встречи, ISO 8601 без часового пояса */
            end: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            /** @description Время создания Записи, ISO 8601 без часового пояса */
            createdAt: string;
        };
        MeetingCreate: {
            eventTypeId: string;
            /** @description Начало Слота, ISO 8601 без часового пояса */
            start: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
        };
        Slot: {
            /** @description Начало Слота, ISO 8601 без часового пояса, напр. 2026-10-10T09:00:00 */
            start: string;
            /** @description Конец Слота, ISO 8601 без часового пояса, напр. 2026-10-10T09:15:00 */
            end: string;
            available: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    Slots_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    Diagnostics_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    Meetings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
        };
    };
    Meetings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
